# Generated by Django 4.2.7 on 2023-11-05 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expends', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expend',
            old_name='title',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='title',
            new_name='detail',
        ),
    ]
