# Generated by Django 4.2.7 on 2023-11-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
